# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for VideoChat
	pod 'OpenTok'
  
target 'VideoChatTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VideoChatUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
